# Generated by Django 4.2.30 on 2026-06-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0003_condominio_blocos'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='autocadastro_ativo',
            field=models.BooleanField(default=False, help_text='Se True, moradores podem se autocadastrar pelo link público.'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='autocadastro_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
