# Generated by Django 4.2.30 on 2026-06-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0004_condominio_autocadastro_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='whatsapp_administradora',
            field=models.CharField(blank=True, default='', help_text='Número (com DDD) da administradora para contato dos inadimplentes.', max_length=20),
        ),
    ]
