# Generated by Django 4.2.29 on 2026-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0002_eleitor_bloco_eleitor_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleitor',
            name='convite_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
