# Generated by Django 4.2.30 on 2026-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0003_eleitor_convite_expira_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleitor',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Se True, o morador não pode autenticar nem votar.'),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='inadimplente',
            field=models.BooleanField(default=False, help_text='Inadimplência por unidade. Se True, o morador acessa mas não pode votar.'),
        ),
    ]
