# Generated by Django 4.2.30 on 2026-06-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0004_eleitor_bloqueado_eleitor_inadimplente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleitor',
            name='cpf_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
