# Generated by Django 4.2.30 on 2026-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0005_alter_eleitor_cpf_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eleitor',
            name='unique_eleitor_apartamento',
        ),
        migrations.AddConstraint(
            model_name='eleitor',
            constraint=models.UniqueConstraint(fields=('condominio', 'bloco', 'apartamento'), name='unique_eleitor_apartamento'),
        ),
    ]
