# Generated by Django 4.2.30 on 2026-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0006_remove_eleitor_unique_eleitor_apartamento_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eleitor',
            name='unique_eleitor_apartamento',
        ),
        migrations.AddConstraint(
            model_name='eleitor',
            constraint=models.UniqueConstraint(fields=('condominio', 'bloco', 'apartamento', 'nome'), name='unique_eleitor_apartamento'),
        ),
    ]
