# Generated by Django 4.2.30 on 2026-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0007_remove_eleitor_unique_eleitor_apartamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleitor',
            name='senha',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='senha_alterada',
            field=models.BooleanField(default=False, help_text='False obriga troca de senha no primeiro acesso.'),
        ),
    ]
