# Generated by Django 4.2.29 on 2026-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0013_solicitacaoexclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidadefacial',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash SHA-256 do CPF do morador. É por ele que o rosto é localizado para a confirmação um-contra-um.', max_length=64),
        ),
        migrations.AddField(
            model_name='identidadefacial',
            name='descriptors',
            field=models.JSONField(blank=True, default=list, help_text='Várias leituras do mesmo rosto (luz/ângulo diferentes). A comparação usa a mais parecida.'),
        ),
        migrations.AlterField(
            model_name='identidadefacial',
            name='descriptor',
            field=models.JSONField(help_text='Vetor facial 128-D (face-api). Leitura principal, mantida por compatibilidade.'),
        ),
    ]
