# Generated by Django 4.2.30 on 2026-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0015_identidade_cpf_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidadefacial',
            name='cadastro_antecipado_em',
            field=models.DateTimeField(blank=True, help_text='Quando o morador cadastrou o rosto pelo link, antes da assembleia.', null=True),
        ),
        migrations.AddField(
            model_name='identidadefacial',
            name='suspeita_duplicidade',
            field=models.BooleanField(default=False, help_text='O rosto do cadastro bateu com o de outro CPF do condomínio. Cada entrada sai com selo até a mesa conferir o documento.'),
        ),
    ]
