# Generated by Django 4.2.29 on 2026-05-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_voto_user_agent_device_info'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voto',
            index=models.Index(fields=['assembleia', 'questao'], name='voto_assemb_quest_idx'),
        ),
        migrations.AddIndex(
            model_name='voto',
            index=models.Index(fields=['assembleia', '-timestamp'], name='voto_assemb_ts_idx'),
        ),
    ]
