# Generated by Django 4.2.30 on 2026-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0003_voto_voto_assemb_quest_idx_voto_voto_assemb_ts_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
