# Generated by Django 4.2.30 on 2026-06-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0004_eleitor_bloqueado_eleitor_inadimplente'),
        ('votos', '0004_voto_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='por_procuracao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voto',
            name='procurador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos_como_procurador', to='eleitores.eleitor'),
        ),
        migrations.AddField(
            model_name='voto',
            name='status',
            field=models.CharField(choices=[('validado', 'Validado'), ('pendente', 'Pendente de validação'), ('rejeitado', 'Rejeitado')], db_index=True, default='validado', max_length=10),
        ),
    ]
