# Generated by Django 4.2.29 on 2026-06-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0006_remove_voto_unique_voto_por_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='decl_apartamento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voto',
            name='decl_bloco',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voto',
            name='decl_nome',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='voto',
            name='grupo_declaracao',
            field=models.UUIDField(blank=True, db_index=True, help_text='Agrupa os votos de uma mesma unidade declarada (para validar em lote).', null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='unidade_declarada',
            field=models.BooleanField(default=False),
        ),
    ]
