# Generated by Django 4.2.29 on 2026-07-17 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0010_eleitor_central_id'),
        ('assembleias', '0017_assembleia_exigir_confirmacao_email'),
        ('votos', '0007_voto_decl_apartamento_voto_decl_bloco_voto_decl_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='eleitor',
            field=models.ForeignKey(blank=True, help_text='Vazio quando o voto é manual (votante_manual preenchido)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='eleitores.eleitor'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='metodo_auth',
            field=models.CharField(choices=[('facial', 'Biometria Facial'), ('webauthn', 'WebAuthn'), ('otp', 'OTP'), ('manual', 'Manual com selfie')], max_length=20),
        ),
        migrations.CreateModel(
            name='VotanteManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('bloco', models.CharField(blank=True, default='', max_length=20)),
                ('apartamento', models.CharField(max_length=20)),
                ('selfie', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assembleia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes_manuais', to='assembleias.assembleia')),
            ],
            options={
                'verbose_name_plural': 'votantes manuais',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddField(
            model_name='voto',
            name='votante_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='votos.votantemanual'),
        ),
    ]
