# Generated by Django 4.2.29 on 2026-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0012_voto_status_pre_inadimplencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='votantemanual',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votantemanual',
            name='conferido_por',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='votantemanual',
            name='conferir_na_mesa',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='votantemanual',
            name='distancia_facial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votantemanual',
            name='motivo_conferencia',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='votantemanual',
            name='unidade_original',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
