# Generated by Django 4.2.30 on 2026-09-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0013_votantemanual_conferido_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='metodo_auth',
            field=models.CharField(choices=[('facial', 'Biometria Facial'), ('selfie', 'Selfie'), ('webauthn', 'WebAuthn'), ('otp', 'OTP'), ('email', 'E-mail sem código'), ('manual', 'Manual com selfie')], max_length=20),
        ),
    ]
