# Generated by Django 4.2.30 on 2026-09-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0014_metodo_auth_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='votantemanual',
            name='cpf_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='votantemanual',
            name='cpf_mascarado',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
