# Generated by Django 4.2.30 on 2026-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='voto_aberto',
            field=models.BooleanField(default=False, help_text='Se True, identifica quem votou (nome/unidade). Se False, anônimo.'),
        ),
        migrations.AddField(
            model_name='enquetevoto',
            name='votante_apartamento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enquetevoto',
            name='votante_bloco',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enquetevoto',
            name='votante_nome',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
