# Generated by Django 4.2.30 on 2026-06-03 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0004_condominio_autocadastro_ativo_and_more'),
        ('enquetes', '0002_enquete_voto_aberto_enquetevoto_votante_apartamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPresenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_presenca', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'Lista de presença manual',
                'verbose_name_plural': 'Listas de presença manual',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PresencaManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('bloco', models.CharField(blank=True, default='', max_length=20)),
                ('apartamento', models.CharField(blank=True, default='', max_length=20)),
                ('selfie', models.TextField(blank=True, default='')),
                ('assinatura', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='enquetes.listapresenca')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
