# Generated by Django 4.2.29 on 2026-07-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0005_listapresenca_codigo_curto'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapresenca',
            name='descricao',
            field=models.TextField(blank=True, default='', help_text='Cabeçalho da lista impressa: data, horários, tipo da assembleia.'),
        ),
    ]
