# Generated by Django 4.2.29 on 2026-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0012_um_voto_por_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencamanual',
            name='conferido_em',
            field=models.DateTimeField(blank=True, help_text='Quando a mesa liberou o registro. Vazio = ainda pendente.', null=True),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='conferido_por',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='conferir_na_mesa',
            field=models.BooleanField(db_index=True, default=False, help_text='Registro que a mesa precisa olhar antes de valer para quórum/voto (unidade alterada, rosto não conferido, CPF fora da planilha).'),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='distancia_facial',
            field=models.FloatField(blank=True, help_text='Distância medida entre o rosto lido e o cadastro (menor = mais parecido). Fica gravada para auditoria.', null=True),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='motivo_conferencia',
            field=models.CharField(blank=True, default='', help_text='Por que precisa de conferência: unidade_alterada, rosto_nao_confere, sem_cadastro, rosto_ambiguo.', max_length=40),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='unidade_original',
            field=models.CharField(blank=True, default='', help_text='Bloco/apto que a planilha trazia, quando o morador corrigiu na hora.', max_length=60),
        ),
    ]
