# Generated by Django 4.2.29 on 2026-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0013_presencamanual_conferido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapresenca',
            name='modo_rapido',
            field=models.BooleanField(default=False, help_text='Lista rápida: sem planilha, sem CPF e sem biometria facial. O morador entra pela foto, com assinatura, aparelho, localização e IP registrados. Feita para reunião marcada na hora.'),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador do aparelho: mostra quando a mesma pessoa assina por vários moradores.', max_length=64),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
