# Generated by Django 4.2.30 on 2026-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0014_lista_rapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencamanual',
            name='cpf_hash',
            field=models.CharField(blank=True, default='', help_text='Hash SHA-256 do CPF/CNPJ informado na presença. Não sai na API.', max_length=64),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='cpf_mascarado',
            field=models.CharField(blank=True, default='', help_text='CPF/CNPJ com o começo e o fim escondidos, para a mesa conferir.', max_length=20),
        ),
        migrations.AddField(
            model_name='presencamanual',
            name='observacao',
            field=models.CharField(blank=True, default='', help_text='Observação do morador: sou procurador, paguei o condomínio hoje etc.', max_length=500),
        ),
        migrations.AlterField(
            model_name='listapresenca',
            name='modo_rapido',
            field=models.BooleanField(default=False, help_text='Lista manual: sem planilha e sem biometria facial. O morador entra pela foto, com CPF, observação e assinatura; aparelho, localização e IP ficam registrados. Quem cria a lista escolhe entre este modo e o da biometria facial.'),
        ),
    ]
