# Generated by Django 4.2.30 on 2026-06-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0004_eleitor_bloqueado_eleitor_inadimplente'),
        ('assembleias', '0007_presenca_assinatura_facial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='eleitor',
            field=models.ForeignKey(blank=True, help_text='Vazio quando a presença é avulsa (morador sem cadastro)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='eleitores.eleitor'),
        ),
    ]
