# Generated by Django 4.2.30 on 2026-06-03 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0008_alter_presenca_eleitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_gravacao', models.URLField(blank=True, default='', help_text='Link da gravação (YouTube, Drive, etc.) — origem da ata')),
                ('transcricao', models.TextField(blank=True, default='', help_text='Transcrição da gravação (colada manualmente ou via IA)')),
                ('resumo', models.TextField(blank=True, default='')),
                ('ata_texto', models.TextField(blank=True, default='', help_text='Ata final, editável pelo síndico')),
                ('provedor_ia', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI Mini')], default='deepseek', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('transcrevendo', 'Transcrevendo'), ('transcrita', 'Transcrita'), ('gerando', 'Gerando ata'), ('pronta', 'Pronta'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro_mensagem', models.CharField(blank=True, default='', max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assembleia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ata', to='assembleias.assembleia')),
            ],
            options={
                'verbose_name_plural': 'atas',
            },
        ),
    ]
