# Generated by Django 4.2.30 on 2026-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0009_ata'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='device_info',
            field=models.CharField(blank=True, default='', help_text='Aparelho/navegador que registrou a presença', max_length=255),
        ),
        migrations.AddField(
            model_name='presenca',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP de onde a presença foi registrada', null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
