# Generated by Django 4.2.30 on 2026-06-03 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0004_condominio_autocadastro_ativo_and_more'),
        ('assembleias', '0010_presenca_device_info_presenca_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('abrir', 'Abrir assembleia'), ('encerrar', 'Encerrar assembleia'), ('validar_procuracao', 'Validar voto por procuração'), ('rejeitar_procuracao', 'Rejeitar voto por procuração'), ('marcar_presenca', 'Marcar presença'), ('transcrever', 'Transcrever gravação'), ('gerar_ata', 'Gerar ata')], max_length=30)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('ator', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assembleia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assembleias.assembleia')),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='condominios.condominio')),
            ],
            options={
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
