# Generated by Django 4.2.29 on 2026-06-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0014_assembleia_codigo_curto'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleia',
            name='modo_multiplas_unidades',
            field=models.CharField(choices=[('sindico', 'Síndico define antecipadamente'), ('morador', 'Morador declara durante a votação')], default='sindico', help_text="Como votam donos de mais de uma unidade. 'sindico': a administração define a cota antecipadamente (votos_permitidos). 'morador': o próprio morador declara suas outras unidades durante a votação, com validação posterior.", max_length=10),
        ),
        migrations.AlterField(
            model_name='assembleia',
            name='codigo_curto',
            field=models.CharField(blank=True, db_index=True, help_text='Código curto do link compartilhável: appvotacao.com.br/vote/<codigo>.', max_length=8, null=True, unique=True),
        ),
    ]
