# Generated by Django 4.2.30 on 2026-07-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0015_questao_liberada'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleia',
            name='link_reuniao',
            field=models.URLField(blank=True, default='', help_text='Link da sala de vídeo (Meet, Zoom, YouTube ao vivo, etc.). Só é revelado ao morador depois que ele registra presença.'),
        ),
    ]
