# Generated by Django 4.2.30 on 2026-09-14 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0020_questao_codigo_curto'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleia',
            name='cadastro_antecedencia_horas',
            field=models.PositiveSmallIntegerField(default=24, help_text='Quantas horas antes do início o cadastro do rosto fecha.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='assembleia',
            name='somente_cadastro_antecipado',
            field=models.BooleanField(default=False, help_text='Só participa quem cadastrou o rosto com antecedência. O cadastro fecha cadastro_antecedencia_horas antes do início e não reabre na hora.'),
        ),
    ]
