# Generated by Django 4.2.30 on 2026-09-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0021_regra_cadastro_antecipado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='cpf_mascarado',
            field=models.CharField(blank=True, default='', help_text='CPF/CNPJ informado na entrada, com o começo e o fim escondidos', max_length=20),
        ),
    ]
